CHRISTINE JOYCE RAMOS, 2ECE-A

In [1]:
#PROBLEM A(POSITIONAL AND LABEL-BASED SLICING)
import pandas as pd

In [5]:
cars = pd.read_csv('cars.csv')

In [6]:
print("Shape of cars:", cars.shape)
print("Column names:", cars.columns.tolist())

Shape of cars: (32, 12)
Column names: ['Model', 'mpg', 'cyl', 'disp', 'hp', 'drat', 'wt', 'qsec', 'vs', 'am', 'gear', 'carb']

In [9]:
cars_6_to_10 = cars.iloc[5:10]

In [10]:
selected_columns = ['Model', 'mpg', 'cyl', 'hp', 'gear']
cars_6_to_10_subset = cars_6_to_10[selected_columns]

In [11]:
display(cars_6_to_10_subset)

        Model   mpg  cyl   hp  gear
5     Valiant  18.1    6  105     3
6  Duster 360  14.3    8  245     3
7   Merc 240D  24.4    4   62     4
8    Merc 230  22.8    4   95     4
9    Merc 280  19.2    6  123     4

In [12]:
#PROBLEM B(MODEL LOOKUP)
toyota = cars[cars['Model'] == 'Toyota Corolla']
display(toyota)

             Model   mpg  cyl  disp  hp  drat     wt  qsec  vs  am  gear  carb
19  Toyota Corolla  33.9    4  71.1  65  4.22  1.835  19.9   1   1     4     1

In [13]:
pontiac = cars[cars['Model'] == 'Pontiac Firebird'][['Model', 'mpg', 'hp', 'wt']]
display(pontiac)

               Model   mpg   hp     wt
24  Pontiac Firebird  19.2  175  3.845

In [14]:
#PROBLEM C(MULTI-MODEL SUBSETTING)
target_models = ['Datsun 710', 'Lotus Europa', 'Ferrari Dino']
target_cols = ['Model', 'mpg', 'cyl', 'hp', 'gear']

In [ ]:
selected_cars = cars[cars['Model'].isin(target_models)